/*
 * Copyright (c) 2026 The Latte Project
 * SPDX-License-Identifier: MIT
 */
package org.lattejava.json;

/**
 * Build-time text-block templates for {@link JSONProcessor} companion generation. Build-time only — not a runtime
 * helper, never added to {@link JSONProcessor#HELPERS}.
 *
 * @author Brian Pontarelli
 */
public final class Templates {
  public static final String ARRAY_OBSERVER = """
        private static String {{field}}ToJSON({{declType}} v) {
          var b = new JSONArrayBuilder();
          for (var e : v) b{{arrayAppend}};
          return b.build();
        }
        private static final class {{obs}} implements JSONArrayObserver<{{declType}}> {
          private final {{declType}} acc = new {{accImpl}}<>();
      {{accumulator}}
      {{stubs}}
          @Override public {{declType}} finish() { return acc; }
          @Override public JSONObjectHandler beginObject() { throw new JSONProcessingException("nested objects in collections unsupported"); }
          @Override public JSONArrayObserver<?> beginArray() { throw new JSONProcessingException("nested collections unsupported"); }
          @Override public void object(Object value) {}
          @Override public void array(Object value) {}
        }
      """;

  public static final String COMPANION = """
      /*
       * Copyright (c) 2026 The Latte Project
       * SPDX-License-Identifier: MIT
       */
      package {{package}};

      import module java.base;
      import {{qualifiedType}};
      import {{internalPkg}}.Conversions;
      import {{internalPkg}}.JSONArrayBuilder;
      import {{internalPkg}}.JSONArrayObserver;
      import {{internalPkg}}.JSONBuilder;
      import {{internalPkg}}.JSONObjectHandler;
      import {{internalPkg}}.JSONObserver;
      import {{internalPkg}}.JSONParser;
      import {{internalPkg}}.JSONProcessingException;
      import {{internalPkg}}.Numbers;
      {{enumImports}}

      /**
       * Generated by org.lattejava.json.JSONProcessor. Do not edit.
       *
       * @author Latte JSON
       */
      public final class {{companion}} implements JSONObserver<{{simpleName}}> {
        {{fields}}

        public static String toJSON({{simpleName}} value) {
          return builder(value).build();
        }

        public static byte[] toJSONBytes({{simpleName}} value) {
          return builder(value).buildBytes();
        }

        private static JSONBuilder builder({{simpleName}} value) {
          return new JSONBuilder({{omitNulls}})
              {{builderCalls}}
              ;
        }

        public static {{simpleName}} fromJSON(String json) {
          var observer = new {{companion}}();
          return new JSONParser().parse(json, observer);
        }

        public static {{simpleName}} fromJSON(byte[] json) {
          var observer = new {{companion}}();
          return new JSONParser().parse(json, observer);
        }

        {{body}}
      }
      """;

  public static final String MAP_OBSERVER = """
        private static String {{field}}ToJSON({{declType}} v) {
          var b = new JSONBuilder({{omitNulls}});
          for (var en : v.entrySet()) b.{{memberCall}};
          return b.build();
        }
        private static final class {{obs}} implements JSONObserver<{{declType}}> {
          private final {{declType}} map = new java.util.LinkedHashMap<>();
      {{accumulator}}
      {{stubs}}
          @Override public void nullValue(String key) { map.put({{keyFromString}}, null); }
          @Override public {{declType}} finish() { return map; }
          @Override public JSONObjectHandler beginObject(String key) { throw new JSONProcessingException("nested objects in collections unsupported"); }
          @Override public JSONArrayObserver<?> beginArray(String key) { throw new JSONProcessingException("nested collections unsupported"); }
          @Override public void object(String key, Object value) {}
          @Override public void array(String key, Object value) {}
        }
      """;

  public static final String OBSERVER_BODY = """
        @Override public void string(String key, String value) {
          switch (key) {
      {{stringCases}}
      {{defaultArm}}
          }
        }
        @Override public void integer(String key, long value) {
          switch (key) {
      {{integerCases}}
      {{defaultArm}}
          }
        }
        @Override public void bigInteger(String key, BigInteger value) {
          switch (key) {
      {{bigIntegerCases}}
      {{defaultArm}}
          }
        }
        @Override public void decimal(String key, BigDecimal value) {
          switch (key) {
      {{decimalCases}}
      {{defaultArm}}
          }
        }
        @Override public void bool(String key, boolean value) {
          switch (key) {
      {{boolCases}}
      {{defaultArm}}
          }
        }
        @Override public void nullValue(String key) {
          switch (key) {
      {{nullCases}}
      {{defaultArm}}
          }
        }
        @Override public JSONObjectHandler beginObject(String key) {
          switch (key) {
      {{beginObjectCases}}
          }
          throw new IllegalStateException("nested objects unsupported in this release");
        }
        @SuppressWarnings("unchecked")
        @Override public void object(String key, Object value) {
          switch (key) {
      {{objectCases}}
      {{defaultArm}}
          }
        }
        @Override public JSONArrayObserver<?> beginArray(String key) {
          switch (key) {
      {{beginArrayCases}}
          }
          throw new IllegalStateException("arrays unsupported in this release");
        }
        @SuppressWarnings("unchecked")
        @Override public void array(String key, Object value) {
          switch (key) {
      {{arrayCases}}
      {{defaultArm}}
          }
        }
        @Override public {{simpleName}} finish() {
          return new {{simpleName}}({{ctorArgs}});
        }
      """;

  private Templates() {
  }
}
