/*
 * Copyright (c) 2026 The Latte Project
 * SPDX-License-Identifier: MIT
 */
package org.lattejava.json;

/**
 * Build-time text-block templates for {@link JSONProcessor} companion generation. Build-time only — not a runtime
 * helper, never added to {@link JSONProcessor#HELPERS}.
 *
 * @author Brian Pontarelli
 */
public final class Templates {
  public static final String COMPANION = """
      /*
       * Copyright (c) 2026 The Latte Project
       * SPDX-License-Identifier: MIT
       */
      package {{package}};

      import module java.base;
      import {{qualifiedType}};
      import {{internalPkg}}.Conversions;
      import {{internalPkg}}.JSONArrayBuilder;
      import {{internalPkg}}.JSONArrayObserver;
      import {{internalPkg}}.JSONBuilder;
      import {{internalPkg}}.JSONObjectHandler;
      import {{internalPkg}}.JSONObserver;
      import {{internalPkg}}.JSONParser;
      import {{internalPkg}}.JSONProcessingException;
      import {{internalPkg}}.Numbers;
      {{enumImports}}

      /**
       * Generated by org.lattejava.json.JSONProcessor. Do not edit.
       *
       * @author Latte JSON
       */
      public final class {{companion}} implements JSONObserver<{{simpleName}}> {
        {{fields}}

        public static String toJSON({{simpleName}} value) {
          return builder(value).build();
        }

        public static byte[] toJSONBytes({{simpleName}} value) {
          return builder(value).buildBytes();
        }

        private static JSONBuilder builder({{simpleName}} value) {
          return new JSONBuilder({{omitNulls}})
              {{builderCalls}}
              ;
        }

        public static {{simpleName}} fromJSON(String json) {
          var observer = new {{companion}}();
          return new JSONParser().parse(json, observer);
        }

        public static {{simpleName}} fromJSON(byte[] json) {
          var observer = new {{companion}}();
          return new JSONParser().parse(json, observer);
        }

        {{body}}
      }
      """;

  private Templates() {
  }
}
